[package]
name = "noir"
type = "bin"
authors = [
    "Shreyas <https://github.com/shreyas-londhe>", 
    "Suyash <https://github.com/suyash67>"
]
compiler_version = ">=1.0.0"

[dependencies]
bignum = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
noir_bigcurve = { path = "../../../open-source-repos/noir_bigcurve" }